[2024-09-11T02:00:01.309+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-11T02:00:01.354+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.seccond_task scheduled__2024-08-29T00:00:00+00:00 [queued]>
[2024-09-11T02:00:01.366+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.seccond_task scheduled__2024-08-29T00:00:00+00:00 [queued]>
[2024-09-11T02:00:01.366+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-09-11T02:00:01.457+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): seccond_task> on 2024-08-29 00:00:00+00:00
[2024-09-11T02:00:01.469+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=12811) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T02:00:01.471+0000] {standard_task_runner.py:63} INFO - Started process 12822 to run task
[2024-09-11T02:00:01.479+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'seccond_task', 'scheduled__2024-08-29T00:00:00+00:00', '--job-id', '3463', '--raw', '--subdir', 'DAGS_FOLDER/7. our_first_dag.py', '--cfg-path', '/tmp/tmpx4cwwuzd']
[2024-09-11T02:00:01.481+0000] {standard_task_runner.py:91} INFO - Job 3463: Subtask seccond_task
[2024-09-11T02:00:01.574+0000] {task_command.py:426} INFO - Running <TaskInstance: our_first_dag_v4.seccond_task scheduled__2024-08-29T00:00:00+00:00 [running]> on host 0359316e7bd1
[2024-09-11T02:00:01.793+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vohoang' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='seccond_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-29T00:00:00+00:00'
[2024-09-11T02:00:01.799+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-11T02:00:01.828+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-11T02:00:01.830+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "hey, I am task2 and will be running after task 1"']
[2024-09-11T02:00:01.854+0000] {subprocess.py:86} INFO - Output:
[2024-09-11T02:00:01.858+0000] {subprocess.py:93} INFO - hey, I am task2 and will be running after task 1
[2024-09-11T02:00:01.860+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-11T02:00:01.861+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-11T02:00:01.954+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v4, task_id=seccond_task, run_id=scheduled__2024-08-29T00:00:00+00:00, execution_date=20240829T000000, start_date=20240911T020001, end_date=20240911T020001
[2024-09-11T02:00:02.172+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-11T02:00:02.226+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T02:00:02.245+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
